### ISSUE TITLE
Unhandled error case in `dis`

### ISSUE THREAD

**Issue by jonocarroll** [coolbutuseless/rbytecode#1]
With the following functions

```r
add_inline <- function(z) { for (i in seq_along(z)) z[i] + 1 }
f <- function(x) x + 1
add_call <- function(z) { for (i in seq_along(z)) f(z[i]) }
```

I am able to run `dis(add_inline)` but not `dis(add_call)`. The latter produces a traceback of

```
> traceback()
3: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
2: stopifnot(!is.null(row_idx), length(row_idx) == 1, !is.na(row_idx))
1: dis(add_call)
```

**Comment by coolbutuseless** [comment]
Just pushed a fix in v0.1.1

What was happening:

* labels are detected in the first pass with the program counter (`PC`) they refer to
* in a subsequent pass, the location of the label is inserted at the `PC` location
* labels can occur at different recursion depths
* in v0.1.0 the PC was assumed to be unique across all depths (a terrible assumption)
* fix: When inserting labels the location for insert depends on both the `PC` for the label **and** the depth at which the label occurs.

**Comment by jonocarroll** [comment]
Awesome, thank you!

I can now compare the two calls - I just need to spend some time understanding the differences. 

![Screenshot from 2024-08-12 09-04-26](https://github.com/user-attachments/assets/79128512-387c-49c7-8df2-144d00dda45f)

The external call is understandably doing a bit more work.

**Comment by coolbutuseless** [comment]
Good luck!

I think there's quite a lot of machinery behind the 'MAKEPROM' call and I'll be interested to see what you find lurking there.
